package com.jetbrains.jetpad.vclang.typechecking.termination;

/*Generated by MPS */

class TestVertex {
  public String myName;
  public String[] myArguments;

  TestVertex(String name, String... arguments) {
    myName = name;
    myArguments = arguments;
  }


  @Override
  public String toString() {
    return myName;
  }
}
