package org.arend.ext.prettyprinting;

public enum PrettyPrinterFlag {
  SHOW_COERCE_DEFINITIONS,
  SHOW_CON_PARAMS,
  SHOW_TUPLE_TYPE,
  SHOW_LOCAL_FIELD_INSTANCE,
  SHOW_GLOBAL_FIELD_INSTANCE,
  SHOW_IMPLICIT_ARGS,
  SHOW_TYPES_IN_LAM,
  SHOW_PREFIX_PATH,
  SHOW_BIN_OP_IMPLICIT_ARGS,
  SHOW_CASE_RESULT_TYPE,
  SHOW_LEVELS
}
