package com.jetbrains.jetpad.vclang.typechecking.termination;

/*Generated by MPS */


public class CompositeCallMatrix extends BaseCallMatrix {
  protected BaseCallMatrix myM1;
  protected BaseCallMatrix myM2;

  public CompositeCallMatrix(BaseCallMatrix m1, BaseCallMatrix m2) {
    super(m1, m2);
    myM1 = m1;
    myM2 = m2;
  }

  @Override
  protected String getMatrixLabel() {
    return myM1.getMatrixLabel() + " o " + myM2.getMatrixLabel();
  }

  @Override
  public Object getCodomain() {
    return myM2.getCodomain();
  }

  @Override
  public Object getDomain() {
    return myM1.getDomain();
  }

  @Override
  protected String[] getColumnLabels() {
    return myM2.getColumnLabels();
  }

  @Override
  protected String[] getRowLabels() {
    return myM1.getRowLabels();
  }


}
