package com.jetbrains.jetpad.vclang.typechecking.termination;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.definition.Definition;
import com.jetbrains.jetpad.vclang.term.context.param.DependentLink;

abstract class LabeledCallMatrix extends BaseCallMatrix<Definition> {

  LabeledCallMatrix(LabeledCallMatrix m) {
    super(m);
  }

  LabeledCallMatrix(int w, int h) {
    super(w, h);
  }

  public abstract Definition getCodomain();

  public abstract Definition getDomain();

  @Override
  protected String[] getColumnLabels() {
    String[] result = new String[getWidth()];
    DependentLink arg = getCodomain().getParameters();
    for (int j = 0; j < getWidth(); j++) {
      result[j] = arg.getName();
      arg = arg.getNext();
    }
    return result;
  }


  @Override
  protected String[] getRowLabels() {
    String[] result = new String[getHeight()];
    DependentLink arg = getDomain().getParameters();
    for (int j = 0; j < getHeight(); j++) {
      result[j] = arg.getName();
      arg = arg.getNext();
    }
    return result;
  }
}
