package org.arend.typechecking.termination;

/*Generated by MPS */

import org.arend.core.definition.Definition;
import org.arend.core.context.param.DependentLink;

abstract class LabeledCallMatrix extends BaseCallMatrix<Definition> {

  LabeledCallMatrix(LabeledCallMatrix m) {
    super(m);
  }

  LabeledCallMatrix(int w, int h) {
    super(w, h);
  }

  public abstract Definition getCodomain();

  public abstract Definition getDomain();
}
