name: gradle
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: eskatos/gradle-command-action@v1.2.1
      with:
        arguments: check --info --no-daemon --stacktrace
    - uses: eskatos/gradle-command-action@v1.2.1
      # Normally, macOS runs faster than the other two
      if: matrix.os == 'macOS-latest' && matrix.java == '11'
      with:
        arguments: "assemble sourcesJar jarDep --info --no-daemon --stacktrace"
    - uses: actions/upload-artifact@master
      if: matrix.os == 'macOS-latest' && matrix.java == '11'
      with:
        name: API
        path: api/build/libs
    - uses: actions/upload-artifact@master
      if: matrix.os == 'macOS-latest' && matrix.java == '11'
      with:
        name: Arend
        path: cli/build/libs
